"""add doc_chunks pgvector store

Revision ID: 79325b4392f5
Revises: ea0df8a14f3e
Create Date: 2026-08-13 13:22:26.892367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '79325b4392f5'
down_revision: Union[str, Sequence[str], None] = 'ea0df8a14f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Requires the pgvector extension. On managed Postgres this may need a superuser/admin to pre-create it
    # (the app role may lack CREATE EXTENSION); locally the trust-auth superuser can create it here.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        'doc_chunks',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('protocol', sa.String(length=32), nullable=False),
        sa.Column('source_url', sa.String(length=512), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=True),
        sa.Column('section', sa.String(length=256), nullable=True),
        sa.Column('chunk_index', sa.Integer(), server_default='0', nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', Vector(384), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_doc_chunks_protocol'), 'doc_chunks', ['protocol'], unique=False)
    # HNSW index for fast cosine-similarity nearest-neighbour search.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_doc_chunks_embedding_hnsw "
        "ON doc_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_chunks_protocol'), table_name='doc_chunks')
    op.drop_table('doc_chunks')
    # ### end Alembic commands ###
